### ISSUE TITLE
Can not excute test

### ISSUE THREAD

**Issue by Giangphanky** [Test-EZ/bug-report#7]
Run **npm test testSuiteRunnerConf.js** but failed

Microsoft Windows [Version 10.0.18363.1256]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7>npm install

up to date, audited 724 packages in 1s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7>npm test testSuiteRunnerConf.js

> webdriverio-6@1.0.0 test
> wdio "testSuiteRunnerConf.js"

2021-01-12T07:12:11.753Z DEBUG @wdio/config:utils: Couldn't find ts-node package, no TypeScript compiling

Execution of 1 spec files started at 2021-01-12T07:12:11.768Z

2021-01-12T07:12:11.770Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-01-12T07:12:11.771Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-01-12T07:12:11.772Z INFO @wdio/local-runner: Start worker 0-0 with arg: testSuiteRunnerConf.js
[0-0] 2021-01-12T07:12:12.174Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\testSuites\Search_course.js
[0-0] 2021-01-12T07:12:12.855Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-01-12T07:12:12.856Z INFO webdriver: [POST] http://0.0.0.1:2/session
[0-0] 2021-01-12T07:12:12.856Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2021-01-12T07:12:12.877Z ERROR webdriver: RequestError: connect ENETUNREACH 0.0.0.1:2
    at ClientRequest.<anonymous> (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\got\dist\source\core\index.js:953:111)
    at Object.onceWrapper (node:events:483:26)
    at ClientRequest.emit (node:events:388:22)
    at ClientRequest.EventEmitter.emit (node:domain:470:12)
    at ClientRequest.origin.emit (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:474:9)
    at Socket.emit (node:events:376:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16)
[0-0] 2021-01-12T07:12:12.878Z ERROR @wdio/runner: Error: Failed to create session.
connect ENETUNREACH 0.0.0.1:2
    at Object.startWebDriverSession (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\webdriver\build\utils.js:34:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Function.newSession (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\webdriver\build\index.js:35:45)
    at Object.exports.remote (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\webdriverio\build\index.js:53:22)
    at Runner._startSession (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\@wdio\runner\build\index.js:123:56)
    at Runner._initSession (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\@wdio\runner\build\index.js:103:25)
    at Runner.run (C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\node_modules\@wdio\runner\build\index.js:52:19)
[0-0] FAILED in chrome - C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7\testSuites\Search_course.js
2021-01-12T07:12:13.000Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01

2021-01-12T07:12:13.002Z INFO @wdio/local-runner: Shutting down spawned worker
2021-01-12T07:12:13.255Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-01-12T07:12:13.256Z INFO @wdio/local-runner: shutting down
npm ERR! code 1
npm ERR! path C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c wdio testSuiteRunnerConf.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Local\npm-cache\_logs\2021-01-12T07_12_13_286Z-debug.log

C:\Users\ADMIN\Downloads\TestEZ\9c2fe83f-8482-4685-b141-94345b72ade7\9c2fe83f-8482-4685-b141-94345b72ade7>

**Comment by TuHuynhVan** [comment]
Did you start your Web driver on port number 2?
`[POST] http://0.0.0.1:2/session`

**Comment by Giangphanky** [comment]
I configured it like the shown image but it still does not work
![image](https://user-images.githubusercontent.com/22991077/104411412-e3339600-559c-11eb-932d-0af5e9911d55.png)

**Comment by TuHuynhVan** [comment]
@Giangphanky You need to start chrome driver on correct port. Please refer.
https://docs.testez.io/docs/web-automation-test/execution
